# Generated by Django 4.0.3 on 2022-03-09 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='commission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
