# Generated by Django 4.0.3 on 2022-04-14 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_log', '0003_trade_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='buy_sell',
            field=models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], default='BUY', max_length=9),
        ),
    ]
