# Generated by Django 4.0.3 on 2022-04-23 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_log', '0004_trade_buy_sell'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trade',
            options={'ordering': ('date',)},
        ),
    ]
